local M = {}

-- Full herb database extracted from eherbs.lic
-- Each entry: { name, type, short, drinkable, doses }
M.database = {
    -- Wehnimer's Landing / Solhaven / Northern Caravansary / Ta'Illistim / River's Rest
    { name = "some acantha leaf", type = "blood", short = "some acantha leaf", drinkable = false, doses = 10 },
    { name = "some wolifrew lichen", type = "minor nerve wound", short = "some wolifrew lichen", drinkable = false, doses = 4 },
    { name = "bolmara potion", type = "major nerve wound", short = "bolmara potion", drinkable = true, doses = 4 },
    { name = "some woth flower", type = "major nerve scar", short = "some woth flower", drinkable = false, doses = 2 },
    { name = "some torban leaf", type = "minor nerve scar", short = "some torban leaf", drinkable = false, doses = 3 },
    { name = "some ambrominas leaf", type = "minor limb wound", short = "some ambrominas leaf", drinkable = false, doses = 4 },
    { name = "some ephlox moss", type = "major limb wound", short = "some ephlox moss", drinkable = false, doses = 4 },
    { name = "some cactacae spine", type = "minor limb scar", short = "some cactacae spine", drinkable = false, doses = 4 },
    { name = "some calamia fruit", type = "major limb scar", short = "some calamia fruit", drinkable = false, doses = 2 },
    { name = "rose-marrow potion", type = "minor head wound", short = "rose-marrow potion", drinkable = true, doses = 4 },
    { name = "some aloeas stem", type = "major head wound", short = "some aloeas stem", drinkable = false, doses = 2 },
    { name = "some haphip root", type = "minor head scar", short = "some haphip root", drinkable = false, doses = 4 },
    { name = "brostheras potion", type = "major head scar", short = "brostheras potion", drinkable = true, doses = 2 },
    { name = "some basal moss", type = "minor organ wound", short = "some basal moss", drinkable = false, doses = 4 },
    { name = "some pothinir grass", type = "major organ wound", short = "some pothinir grass", drinkable = false, doses = 2 },
    { name = "talneo potion", type = "minor organ scar", short = "talneo potion", drinkable = true, doses = 4 },
    { name = "wingstem potion", type = "major organ scar", short = "wingstem potion", drinkable = true, doses = 2 },
    { name = "bur-clover potion", type = "missing eye", short = "bur-clover potion", drinkable = true, doses = 1 },
    { name = "some sovyn clove", type = "severed limb", short = "some sovyn clove", drinkable = false, doses = 1 },

    -- Solhaven bulk (Do Not Buy)
    { name = "bunch of acantha leaf", type = "blood", short = "bunch of acantha leaf", drinkable = false, doses = 50 },
    { name = "bunch of wolifrew lichen", type = "minor nerve wound", short = "bunch of wolifrew lichen", drinkable = false, doses = 50 },
    { name = "large bolmara potion", type = "major nerve wound", short = "large bolmara potion", drinkable = true, doses = 7 },
    { name = "bunch of woth flower", type = "major nerve scar", short = "bunch of woth flower", drinkable = false, doses = 50 },
    { name = "bunch of torban leaf", type = "minor nerve scar", short = "bunch of torban leaf", drinkable = false, doses = 50 },
    { name = "bunch of ambrominas leaf", type = "minor limb wound", short = "bunch of ambrominas leaf", drinkable = false, doses = 50 },
    { name = "bunch of ephlox moss", type = "major limb wound", short = "bunch of ephlox moss", drinkable = false, doses = 50 },
    { name = "bunch of cactacae spine", type = "minor limb scar", short = "bunch of cactacae spine", drinkable = false, doses = 50 },
    { name = "bunch of calamia fruit", type = "major limb scar", short = "bunch of calamia fruit", drinkable = false, doses = 50 },
    { name = "large rose-marrow potion", type = "minor head wound", short = "large rose-marrow potion", drinkable = true, doses = 7 },
    { name = "bunch of aloeas stem", type = "major head wound", short = "bunch of aloeas stem", drinkable = false, doses = 50 },
    { name = "bunch of haphip root", type = "minor head scar", short = "bunch of haphip root", drinkable = false, doses = 50 },
    { name = "large brostheras potion", type = "major head scar", short = "large brostheras potion", drinkable = true, doses = 7 },
    { name = "bunch of basal moss", type = "minor organ wound", short = "bunch of basal moss", drinkable = false, doses = 50 },
    { name = "bunch of pothinir grass", type = "major organ wound", short = "bunch of pothinir grass", drinkable = false, doses = 50 },
    { name = "large talneo potion", type = "minor organ scar", short = "large large talneo potion", drinkable = true, doses = 7 },
    { name = "large wingstem potion", type = "major organ scar", short = "large wingstem potion", drinkable = true, doses = 7 },
    { name = "large bur-clover potion", type = "missing eye", short = "large bur-clover potion", drinkable = true, doses = 7 },
    { name = "bunch of sovyn clove", type = "severed limb", short = "bunch of sovyn clove", drinkable = false, doses = 50 },

    -- Ta'Vaalor
    { name = "tincture of acantha", type = "blood", short = "tincture of acantha", drinkable = true, doses = 10 },
    { name = "tincture of ambrominas", type = "minor limb wound", short = "tincture of ambrominas", drinkable = true, doses = 4 },
    { name = "tincture of wolifrew", type = "minor nerve wound", short = "tincture of wolifrew", drinkable = true, doses = 4 },
    { name = "tincture of rose-marrow", type = "minor head wound", short = "tincture of rose-marrow", drinkable = true, doses = 4 },
    { name = "tincture of basal", type = "minor organ wound", short = "tincture of basal", drinkable = true, doses = 4 },
    { name = "tincture of ephlox", type = "major limb wound", short = "tincture of ephlox", drinkable = true, doses = 4 },
    { name = "tincture of bolmara", type = "major nerve wound", short = "tincture of bolmara", drinkable = true, doses = 4 },
    { name = "tincture of aloeas", type = "major head wound", short = "tincture of aloeas", drinkable = true, doses = 2 },
    { name = "tincture of pothinir", type = "major organ wound", short = "tincture of pothinir", drinkable = true, doses = 2 },
    { name = "tincture of cactacae", type = "minor limb scar", short = "tincture of cactacae", drinkable = true, doses = 4 },
    { name = "tincture of torban", type = "minor nerve scar", short = "tincture of torban", drinkable = true, doses = 3 },
    { name = "tincture of haphip", type = "minor head scar", short = "tincture of haphip", drinkable = true, doses = 4 },
    { name = "tincture of talneo", type = "minor organ scar", short = "tincture of talneo", drinkable = true, doses = 4 },
    { name = "tincture of calamia", type = "major limb scar", short = "tincture of calamia", drinkable = true, doses = 2 },
    { name = "tincture of woth", type = "major nerve scar", short = "tincture of woth", drinkable = true, doses = 2 },
    { name = "tincture of brostheras", type = "major head scar", short = "tincture of brostheras", drinkable = true, doses = 2 },
    { name = "tincture of wingstem", type = "major organ scar", short = "tincture of wingstem", drinkable = true, doses = 2 },
    { name = "tincture of bur-clover", type = "missing eye", short = "tincture of bur-clover", drinkable = true, doses = 1 },
    { name = "tincture of sovyn", type = "severed limb", short = "tincture of sovyn", drinkable = true, doses = 1 },

    -- Zul Logoth
    { name = "grey mushroom potion", type = "blood", short = "grey mushroom potion", drinkable = true, doses = 7 },
    { name = "green mushroom potion", type = "blood", short = "green mushroom potion", drinkable = true, doses = 5 },
    { name = "bubbling brown ale", type = "minor limb wound", short = "bubbling brown ale", drinkable = true, doses = 3 },
    { name = "thick foggy ale", type = "minor nerve wound", short = "thick foggy ale", drinkable = true, doses = 3 },
    { name = "rusty red ale", type = "minor head wound", short = "rusty red ale", drinkable = true, doses = 3 },
    { name = "chunky black ale", type = "minor organ wound", short = "chunky black ale", drinkable = true, doses = 3 },
    { name = "crushed cavegrass tea", type = "major limb wound", short = "crushed cavegrass tea", drinkable = true, doses = 2 },
    { name = "glowing mold tea", type = "major nerve wound", short = "glowing mold tea", drinkable = true, doses = 2 },
    { name = "sticky lichen tea", type = "major head wound", short = "sticky lichen tea", drinkable = true, doses = 2 },
    { name = "roasted ratweed tea", type = "major organ wound", short = "roasted ratweed tea", drinkable = true, doses = 2 },
    { name = "spotted toadstool ale", type = "minor limb scar", short = "spotted toadstool ale", drinkable = true, doses = 2 },
    { name = "dark frothing ale", type = "minor nerve scar", short = "dark frothing ale", drinkable = true, doses = 2 },
    { name = "dull crimson ale", type = "minor head scar", short = "dull crimson ale", drinkable = true, doses = 2 },
    { name = "brown weedroot ale", type = "minor organ scar", short = "brown weedroot ale", drinkable = true, doses = 2 },
    { name = "stalactite brew", type = "major limb scar", short = "stalactite brew", drinkable = true, doses = 2 },
    { name = "stalagmite brew", type = "major nerve scar", short = "stalagmite brew", drinkable = true, doses = 2 },
    { name = "stone soot brew", type = "major head scar", short = "stone soot brew", drinkable = true, doses = 2 },
    { name = "dirty crevice brew", type = "major organ scar", short = "dirty crevice brew", drinkable = true, doses = 2 },
    { name = "dirty rat fur potion", type = "missing eye", short = "dirty rat fur potion", drinkable = true, doses = 1 },
    { name = "grainy black potion", type = "severed limb", short = "grainy black potion", drinkable = true, doses = 1 },
    { name = "milky white potion", type = "lifekeep", short = "milky white potion", drinkable = true, doses = 3 },

    -- Cysaegir / Ravelin
    { name = "tincture of acantha", type = "blood", short = "tincture of acantha", drinkable = true, doses = 10 },
    { name = "tincture of ambrominas", type = "minor limb wound", short = "tincture of ambrominas", drinkable = true, doses = 4 },
    { name = "tincture of wolifrew", type = "minor nerve wound", short = "tincture of wolifrew", drinkable = true, doses = 4 },
    { name = "tincture of rose-marrow", type = "minor head wound", short = "tincture of rose-marrow", drinkable = true, doses = 4 },
    { name = "tincture of basal", type = "minor organ wound", short = "tincture of basal", drinkable = true, doses = 4 },
    { name = "tincture of ephlox", type = "major limb wound", short = "tincture of ephlox", drinkable = true, doses = 4 },
    { name = "tincture of bolmara", type = "major nerve wound", short = "tincture of bolmara", drinkable = true, doses = 4 },
    { name = "tincture of aloeas", type = "major head wound", short = "tincture of aloeas", drinkable = true, doses = 2 },
    { name = "tincture of pothinir", type = "major organ wound", short = "tincture of pothinir", drinkable = true, doses = 2 },
    { name = "tincture of cactacae", type = "minor limb scar", short = "tincture of cactacae", drinkable = true, doses = 4 },
    { name = "tincture of torban", type = "minor nerve scar", short = "tincture of torban", drinkable = true, doses = 3 },
    { name = "tincture of haphip", type = "minor head scar", short = "tincture of haphip", drinkable = true, doses = 4 },
    { name = "tincture of talneo", type = "minor organ scar", short = "tincture of talneo", drinkable = true, doses = 4 },
    { name = "tincture of calamia", type = "major limb scar", short = "tincture of calamia", drinkable = true, doses = 2 },
    { name = "tincture of woth", type = "major nerve scar", short = "tincture of woth", drinkable = true, doses = 2 },
    { name = "tincture of brostheras", type = "major head scar", short = "tincture of brostheras", drinkable = true, doses = 2 },
    { name = "tincture of wingstem", type = "major organ scar", short = "tincture of wingstem", drinkable = true, doses = 2 },
    { name = "tincture of bur-clover", type = "missing eye", short = "tincture of bur-clover", drinkable = true, doses = 1 },
    { name = "tincture of sovyn", type = "severed limb", short = "tincture of sovyn", drinkable = true, doses = 1 },

    -- Ta'Illistim (Herbalist 2)
    { name = "tincture of acantha", type = "blood", short = "tincture of acantha", drinkable = true, doses = 20 },
    { name = "tincture of wolifrew", type = "minor nerve wound", short = "tincture of wolifrew", drinkable = true, doses = 20 },
    { name = "tincture of torban", type = "minor nerve scar", short = "tincture of torban", drinkable = true, doses = 10 },
    { name = "tincture of woth", type = "major nerve scar", short = "tincture of woth", drinkable = true, doses = 10 },
    { name = "tincture of ambrominas", type = "minor limb wound", short = "tincture of ambrominas", drinkable = true, doses = 20 },
    { name = "tincture of basal", type = "minor organ wound", short = "tincture of basal", drinkable = true, doses = 20 },
    { name = "tincture of ephlox", type = "major limb wound", short = "tincture of ephlox", drinkable = true, doses = 20 },
    { name = "tincture of pothinir", type = "major organ wound", short = "tincture of pothinir", drinkable = true, doses = 10 },
    { name = "tincture of aloeas", type = "major head wound", short = "tincture of aloeas", drinkable = true, doses = 10 },
    { name = "tincture of rose-marrow", type = "minor head wound", short = "tincture of rose-marrow", drinkable = true, doses = 20 },
    { name = "tincture of cactacae", type = "minor limb scar", short = "tincture of cactacae", drinkable = true, doses = 10 },
    { name = "tincture of calamia", type = "major limb scar", short = "tincture of calamia", drinkable = true, doses = 10 },
    { name = "tincture of haphip", type = "minor head scar", short = "tincture of haphip", drinkable = true, doses = 10 },
    { name = "tincture of brostheras", type = "major head scar", short = "tincture of brostheras", drinkable = true, doses = 10 },
    { name = "tincture of bolmara", type = "major nerve wound", short = "tincture of bolmara", drinkable = true, doses = 20 },
    { name = "tincture of talneo", type = "minor organ scar", short = "tincture of talneo", drinkable = true, doses = 10 },
    { name = "tincture of bur-clover", type = "missing eye", short = "tincture of bur-clover", drinkable = true, doses = 10 },
    { name = "tincture of wingstem", type = "major organ scar", short = "tincture of wingstem", drinkable = true, doses = 10 },
    { name = "tincture of sovyn", type = "severed limb", short = "tincture of sovyn", drinkable = true, doses = 10 },

    -- Teras (Kharam-Dzu)
    { name = "flagon of Olak's Ol'style ale", type = "blood", short = "Olak's Ol'style ale", drinkable = true, doses = 3 },
    { name = "barrel of Olak's Ol'style ale", type = "blood", short = "Olak's Ol'style ale", drinkable = true, doses = 10 },
    { name = "flagon of Lost Dogwater ale", type = "minor limb wound", short = "Lost Dogwater ale", drinkable = true, doses = 3 },
    { name = "barrel of Lost Dogwater ale", type = "minor limb wound", short = "Lost Dogwater ale", drinkable = true, doses = 10 },
    { name = "flagon of Orc's Head ale", type = "minor nerve wound", short = "Orc's Head ale", drinkable = true, doses = 3 },
    { name = "barrel of Orc's Head ale", type = "minor nerve wound", short = "Orc's Head ale", drinkable = true, doses = 10 },
    { name = "flagon of Semak's Smooth ale", type = "minor head wound", short = "Semak's Smooth ale", drinkable = true, doses = 3 },
    { name = "barrel of Semak's Smooth ale", type = "minor head wound", short = "Semak's Smooth ale", drinkable = true, doses = 3 },
    { name = "flagon of Mama Dwarf's ale", type = "minor organ wound", short = "Mama Dwarf's ale", drinkable = true, doses = 3 },
    { name = "barrel of Mama Dwarf's ale", type = "minor organ wound", short = "Mama Dwarf's ale", drinkable = true, doses = 10 },
    { name = "flagon of Bloody Krolvin ale", type = "blood", short = "Bloody Krolvin ale", drinkable = true, doses = 3 },
    { name = "barrel of Bloody Krolvin ale", type = "blood", short = "Bloody Krolvin ale", drinkable = true, doses = 10 },
    { name = "flagon of Golden Goose ale", type = "major limb wound", short = "Golden Goose ale", drinkable = true, doses = 3 },
    { name = "barrel of Golden Goose ale", type = "major limb wound", short = "Golden Goose ale", drinkable = true, doses = 10 },
    { name = "flagon of Kenar's Dropjaw ale", type = "major nerve wound", short = "Kenar's Dropjaw ale", drinkable = true, doses = 3 },
    { name = "barrel of Kenar's Dropjaw ale", type = "major nerve wound", short = "Kenar's Dropjaw ale", drinkable = true, doses = 10 },
    { name = "flagon of Dark Swampwater ale", type = "major head wound", short = "Dark Swampwater ale", drinkable = true, doses = 3 },
    { name = "barrel of Dark Swampwater ale", type = "major head wound", short = "Dark Swampwater ale", drinkable = true, doses = 10 },
    { name = "flagon of Aged Schooner ale", type = "major organ wound", short = "Aged Schooner ale", drinkable = true, doses = 3 },
    { name = "barrel of Aged Schooner ale", type = "major organ wound", short = "Aged Schooner ale", drinkable = true, doses = 10 },
    { name = "flagon of Bearded Ladies' ale", type = "minor limb scar", short = "Bearded Ladies' ale", drinkable = true, doses = 3 },
    { name = "barrel of Bearded Ladies' ale", type = "minor limb scar", short = "Bearded Ladies' ale", drinkable = true, doses = 10 },
    { name = "flagon of Miner's Muddy ale", type = "minor nerve scar", short = "Miner's Muddy ale", drinkable = true, doses = 3 },
    { name = "barrel of Miner's Muddy ale", type = "minor nerve scar", short = "Miner's Muddy ale", drinkable = true, doses = 10 },
    { name = "flagon of Agrak's Amber ale", type = "minor head scar", short = "Agrak's Amber ale", drinkable = true, doses = 3 },
    { name = "barrel of Agrak's Amber ale", type = "minor head scar", short = "Agrak's Amber ale", drinkable = true, doses = 10 },
    { name = "flagon of Gert's Homemade ale", type = "minor organ scar", short = "Gert's Homemade ale", drinkable = true, doses = 3 },
    { name = "barrel of Gert's Homemade ale", type = "minor organ scar", short = "Gert's Homemade ale", drinkable = true, doses = 10 },
    { name = "flagon of Mad Mutt Frothy ale", type = "major limb scar", short = "Mad Mutt Frothy ale", drinkable = true, doses = 3 },
    { name = "barrel of Mad Mutt Frothy ale", type = "major limb scar", short = "Mad Mutt Frothy ale", drinkable = true, doses = 10 },
    { name = "flagon of Dacra's Dream ale", type = "major nerve scar", short = "Dacra's Dream ale", drinkable = true, doses = 3 },
    { name = "barrel of Dacra's Dream ale", type = "major nerve scar", short = "Dacra's Dream ale", drinkable = true, doses = 10 },
    { name = "flagon of Reaper's Red ale", type = "major head scar", short = "Reaper's Red ale", drinkable = true, doses = 3 },
    { name = "barrel of Reaper's Red ale", type = "major head scar", short = "Reaper's Red ale", drinkable = true, doses = 10 },
    { name = "barrel of Reaper's Red ale", type = "major head scar", short = "Reaper's Red ale", drinkable = true, doses = 10 },
    { name = "flagon of Wort's Winter ale", type = "major organ scar", short = "Wort's Winter ale", drinkable = true, doses = 3 },
    { name = "barrel of Wort's Winter ale", type = "major organ scar", short = "Wort's Winter ale", drinkable = true, doses = 10 },
    { name = "flagon of Volcano Vision ale", type = "missing eye", short = "Volcano Vision ale", drinkable = true, doses = 3 },
    { name = "barrel of Volcano Vision ale", type = "missing eye", short = "Volcano Vision ale", drinkable = true, doses = 10 },
    { name = "flagon of Captn' Pegleg's ale", type = "severed limb", short = "Captn' Pegleg's ale", drinkable = true, doses = 3 },
    { name = "barrel of Captn' Pegleg's ale", type = "severed limb", short = "Captn' Pegleg's ale", drinkable = true, doses = 10 },
    { name = "flagon of Dead Man's Pale ale", type = "lifekeep", short = "Dead Man's Pale ale", drinkable = true, doses = 3 },
    { name = "barrel of Dead Man's Pale ale", type = "lifekeep", short = "Dead Man's Pale ale", drinkable = true, doses = 10 },
    { name = "flagon of Dragon's Blood porter", type = "raisedead", short = "Dragon's Blood porter", drinkable = true, doses = 1 },

    -- Icemule Trace / Hinterwilds
    { name = "Dabbings Family special tart", type = "minor limb wound", short = "Family special tart", drinkable = true, doses = 10 },
    { name = "Leaftoe's lichen tart", type = "minor nerve wound", short = "lichen tart", drinkable = true, doses = 10 },
    { name = "candied ptarmigan feather", type = "severed limb", short = "ptarmigan feather", drinkable = false, doses = 1 },
    { name = "earthworm potion", type = "major organ scar", short = "earthworm potion", drinkable = true, doses = 2 },
    { name = "elk horn potion", type = "minor head wound", short = "elk horn potion", drinkable = true, doses = 4 },
    { name = "gelatinous elk fat tart", type = "minor limb scar", short = "elk fat tart", drinkable = true, doses = 10 },
    { name = "iceberry tart", type = "blood", short = "iceberry tart", drinkable = true, doses = 10 },
    { name = "rock lizard potion", type = "minor organ scar", short = "rock lizard potion", drinkable = true, doses = 4 },
    { name = "slice of Ma Leaftoe's Special", type = "minor nerve scar", short = "Ma Leaftoe's Special", drinkable = false, doses = 5 },
    { name = "slice of pickled walrus blubber", type = "major limb scar", short = "pickled walrus blubber", drinkable = false, doses = 2 },
    { name = "slice of sparrowhawk pie", type = "minor head scar", short = "sparrowhawk pie", drinkable = true, doses = 5 },
    { name = "small egg and tundra grass tart", type = "minor organ wound", short = "tundra grass tart", drinkable = true, doses = 5 },
    { name = "snowflake elixir", type = "major nerve wound", short = "snowflake elixir", drinkable = true, doses = 4 },
    { name = "some frog's bone porridge", type = "major limb wound", short = "frog's bone porridge", drinkable = false, doses = 4 },
    { name = "starfish potion", type = "missing eye", short = "starfish potion", drinkable = true, doses = 1 },
    { name = "tiny cup of polar bear fat soup", type = "major head scar", short = "polar bear fat soup", drinkable = true, doses = 2 },
    { name = "tiny flower-shaped tart", type = "major nerve scar", short = "flower-shaped tart", drinkable = true, doses = 2 },
    { name = "tiny musk ox tart", type = "major organ wound", short = "musk ox tart", drinkable = true, doses = 2 },
    { name = "tiny ram's bladder tart", type = "major head wound", short = "ram's bladder tart", drinkable = true, doses = 2 },

    -- Pinefar Trading Post
    { name = "some acantha leaf tea", type = "blood", short = "acantha leaf tea", drinkable = true, doses = 10 },
    { name = "some sweetfern tea", type = "minor limb wound", short = "sweetfern tea", drinkable = true, doses = 4 },
    { name = "some red lichen tea", type = "minor nerve wound", short = "red lichen tea", drinkable = true, doses = 4 },
    { name = "some feverfew tea", type = "minor head wound", short = "feverfew tea", drinkable = true, doses = 4 },
    { name = "some ginkgo nut tea", type = "minor organ wound", short = "ginkgo nut tea", drinkable = true, doses = 4 },
    { name = "some sassafras tea", type = "blood", short = "sassafras tea", drinkable = true, doses = 2 },
    { name = "sweetfern potion", type = "major limb wound", short = "sweetfern potion", drinkable = true, doses = 4 },
    { name = "red lichen potion", type = "major nerve wound", short = "red lichen potion", drinkable = true, doses = 4 },
    { name = "feverfew potion", type = "major head wound", short = "feverfew potion", drinkable = true, doses = 4 },
    { name = "ginkgo nut potion", type = "major organ wound", short = "ginkgo nut potion", drinkable = true, doses = 4 },
    { name = "manroot tea", type = "minor limb scar", short = "manroot tea", drinkable = true, doses = 2 },
    { name = "valerian root tea", type = "minor nerve scar", short = "valerian root tea", drinkable = true, doses = 2 },
    { name = "pennyroyal tea", type = "minor head scar", short = "pennyroyal tea", drinkable = true, doses = 2 },
    { name = "wyrmwood root tea", type = "minor organ scar", short = "wyrmwood root tea", drinkable = true, doses = 2 },
    { name = "manroot potion", type = "major limb scar", short = "manroot potion", drinkable = true, doses = 2 },
    { name = "valerian root potion", type = "major nerve scar", short = "valerian root potion", drinkable = true, doses = 2 },
    { name = "pennyroyal potion", type = "major head scar", short = "pennyroyal potion", drinkable = true, doses = 2 },
    { name = "wyrmwood root potion", type = "major organ scar", short = "wyrmwood root potion", drinkable = true, doses = 2 },
    { name = "daggit root potion", type = "missing eye", short = "daggit root potion", drinkable = true, doses = 1 },
    { name = "angelica root potion", type = "severed limb", short = "angelica root potion", drinkable = true, doses = 1 },
    { name = "earwort potion", type = "disease", short = "earwort potion", drinkable = true, doses = 1 },

    -- Kraken's Fall
    { name = "some acantha leaf", type = "blood", short = "acantha leaf", drinkable = false, doses = 10 },
    { name = "some wolifrew lichen", type = "minor nerve wound", short = "wolifrew lichen", drinkable = false, doses = 4 },
    { name = "some torban leaf", type = "minor nerve scar", short = "torban leaf", drinkable = false, doses = 4 },
    { name = "bolmara elixir", type = "major nerve wound", short = "bolmara elixir", drinkable = true, doses = 4 },
    { name = "some woth flower", type = "major nerve scar", short = "woth flower", drinkable = false, doses = 3 },
    { name = "rose-marrow elixir", type = "minor head wound", short = "rose-marrow elixir", drinkable = true, doses = 4 },
    { name = "some haphip root", type = "minor head scar", short = "haphip root", drinkable = false, doses = 4 },
    { name = "some aloeas stem", type = "major head wound", short = "aloeas stem", drinkable = false, doses = 2 },
    { name = "brostheras elixir", type = "major head scar", short = "brostheras elixir", drinkable = true, doses = 2 },
    { name = "ball of basal moss", type = "minor organ wound", short = "basal moss", drinkable = false, doses = 7 },
    { name = "talneo elixir", type = "minor organ scar", short = "talneo elixir", drinkable = true, doses = 4 },
    { name = "some pothinir grass", type = "major organ wound", short = "pothinir grass", drinkable = false, doses = 2 },
    { name = "wingstem elixir", type = "major organ scar", short = "wingstem elixir", drinkable = true, doses = 2 },
    { name = "some ambrominas leaf", type = "minor limb wound", short = "ambrominas leaf", drinkable = false, doses = 4 },
    { name = "some cactacae spine", type = "minor limb scar", short = "cactacae spine", drinkable = false, doses = 4 },
    { name = "ball of ephlox moss", type = "major limb wound", short = "ephlox moss", drinkable = false, doses = 4 },
    { name = "some calamia fruit", type = "major limb scar", short = "calamia fruit", drinkable = false, doses = 2 },
    { name = "cumin-rubbed sovyn clove", type = "severed limb", short = "sovyn clove", drinkable = false, doses = 1 },
    { name = "bur-clover elixir", type = "missing eye", short = "bur-clover elixir", drinkable = true, doses = 1 },

    -- Mist Harbor (Isle of Four Winds)
    { name = "some fragrant woth flower", type = "major nerve scar", short = "fragrant woth flower", drinkable = false, doses = 3 },
    { name = "some dirty haphip root", type = "minor head scar", short = "dirty haphip root", drinkable = false, doses = 4 },
    { name = "sticky ball of basal moss", type = "minor organ wound", short = "ball of basal moss", drinkable = false, doses = 7 },
    { name = "gooey ball of ephlox moss", type = "major limb wound", short = "ball of ephlox moss", drinkable = false, doses = 4 },
    { name = "some sugary ambrominas leaf", type = "minor limb wound", short = "sugary ambrominas leaf", drinkable = false, doses = 4 },
    { name = "some fresh torban leaf", type = "minor nerve scar", short = "fresh torban leaf", drinkable = false, doses = 4 },
    { name = "some spicy acantha leaf", type = "blood", short = "spicy acantha leaf", drinkable = false, doses = 10 },
    { name = "small sovyn clove", type = "severed limb", short = "small sovyn clove", drinkable = false, doses = 1 },
    { name = "some bright green pothinir grass", type = "major organ wound", short = "some bright pothinir grass", drinkable = false, doses = 2 },
    { name = "some withered aloeas stem", type = "major head wound", short = "withered aloeas stem", drinkable = false, doses = 2 },
    { name = "some ripe calamia fruit", type = "major limb scar", short = "ripe calamia fruit", drinkable = false, doses = 2 },
    { name = "some prickly cactacae spine", type = "minor limb scar", short = "prickly cactacae spine", drinkable = false, doses = 4 },
    { name = "some dry wolifrew lichen", type = "minor nerve wound", short = "dry wolifrew lichen", drinkable = false, doses = 4 },
    { name = "crystalline rose-marrow elixir", type = "minor head wound", short = "rose-marrow elixir", drinkable = true, doses = 4 },
    { name = "crystalline talneo elixir", type = "minor organ scar", short = "talneo elixir", drinkable = true, doses = 4 },
    { name = "crystalline brostheras elixir", type = "major head scar", short = "brostheras elixir", drinkable = true, doses = 2 },
    { name = "crystalline bolmara elixir", type = "major nerve wound", short = "bolmara elixir", drinkable = true, doses = 4 },
    { name = "crystalline wingstem elixir", type = "major organ scar", short = "wingstem elixir", drinkable = true, doses = 2 },
    { name = "crystalline bur-clover elixir", type = "missing eye", short = "bur-clover elixir", drinkable = true, doses = 1 },

    -- River's Rest
    { name = "beaker of malted winterberry brew", type = "minor head wound", short = "beaker of winterberry brew", drinkable = true, doses = 4 },
    { name = "beaker of winterberry brew", type = "minor head wound", short = "winterberry brew", drinkable = true, doses = 4 },

    -- Forageable
    { name = "yabathilium fruit", type = "blood", short = "yabathilium fruit", drinkable = false, doses = 1 },
    { name = "ochre-colored fungus", type = "poison", short = "ochre-colored fungus", drinkable = false, doses = 1 },
    { name = "red nettle berry", type = "poison", short = "red nettle berry", drinkable = false, doses = 1 },

    -- Skinnable
    { name = "pulsating firethorn shoot", type = "poison", short = "pulsating firethorn shoot", drinkable = false, doses = 1 },

    -- Alchemical
    { name = "tincture of yabathilium", type = "blood", short = "tincture of yabathilium", drinkable = true, doses = 1 },
    { name = "dimly glowing sky-blue potion", type = "disease", short = "sky-blue potion", drinkable = true, doses = 4 },
    { name = "dimly glowing sea-green potion", type = "poison", short = "sea-green potion", drinkable = true, doses = 4 },
}

function M.find_by_type(wound_type, opts)
    opts = opts or {}
    for _, herb in ipairs(M.database) do
        if herb.type == wound_type then
            if opts.prefer_drinkable and herb.drinkable then return herb end
            if opts.prefer_edible and not herb.drinkable then return herb end
            if not opts.prefer_drinkable and not opts.prefer_edible then return herb end
        end
    end
    -- Fallback: any herb of the type
    for _, herb in ipairs(M.database) do
        if herb.type == wound_type then return herb end
    end
    return nil
end

function M.is_drinkable(noun)
    local n = noun:lower()
    return Regex.test("potion|tincture|elixir|tea|ale|soup|brew|porter|flagon", n)
end

function M.list_types()
    return {
        "blood", "poison", "disease", "lifekeep", "raisedead",
        "major head wound", "minor head wound",
        "major head scar", "minor head scar",
        "major nerve wound", "minor nerve wound",
        "major nerve scar", "minor nerve scar",
        "major organ wound", "minor organ wound",
        "major organ scar", "minor organ scar",
        "major limb wound", "minor limb wound",
        "major limb scar", "minor limb scar",
        "severed limb", "missing eye",
    }
end

return M
