--- @revenant-script
--- name: calibrate_creaturebar
--- version: 1.0.0
--- author: Elanthia Online
--- contributors: Nisugi
--- game: gs
--- tags: hunting, combat, creatures
--- description: Visual tool to calibrate body part coordinates for CreatureBar silhouettes
---
--- Original Lich5 authors: Elanthia Online, Nisugi
--- Ported to Revenant Lua from calibrate_creaturebar.lic v1.0
---
--- NOTE: The original script uses GTK3 for its GUI. Revenant uses egui.
--- This port provides a terminal-based calibration interface since egui
--- widget support is still evolving. The coordinate data format is preserved
--- for compatibility with CreatureBar.

local VERSION = "1.0.0"

--------------------------------------------------------------------------------
-- Configuration
--------------------------------------------------------------------------------

local DATA_DIR  = GameState.data_dir or "data"
local CONFIG_DIR = DATA_DIR .. "/creature_bar"
local CONFIG_FILE = CONFIG_DIR .. "/config.yaml"
local SILHOUETTE_DIR = CONFIG_DIR .. "/silhouettes"
local SILHOUETTE_CONFIG_DIR = CONFIG_DIR .. "/configs"

local BODY_PARTS = {
    "head", "neck", "chest", "abdomen", "back",
    "leftArm", "rightArm", "leftHand", "rightHand",
    "leftLeg", "rightLeg", "leftFoot", "rightFoot",
    "leftEye", "rightEye", "nerves",
}

local WOUND_RANKS = { 1, 2, 3 }

--------------------------------------------------------------------------------
-- State
--------------------------------------------------------------------------------

local current_part_index = 1
local current_rank = 1
local current_family = "default"
local current_subfolder = "default"

-- coordinates[family][part][rank] = { x = N, y = N }
local coordinates = {}

-- Available silhouette families
local families = { "default" }

--------------------------------------------------------------------------------
-- File I/O helpers
--------------------------------------------------------------------------------

local function ensure_dir(path)
    os.execute('mkdir -p "' .. path .. '"')
end

local function file_exists(path)
    local f = io.open(path, "r")
    if f then f:close(); return true end
    return false
end

--- Simple YAML-like config writer for coordinate data
local function save_config(family, data)
    ensure_dir(SILHOUETTE_CONFIG_DIR)
    local filepath = SILHOUETTE_CONFIG_DIR .. "/" .. family .. ".cfg"
    local f = io.open(filepath, "w")
    if not f then
        echo("Failed to save config: " .. filepath)
        return
    end

    f:write("# CreatureBar Calibration Config\n")
    f:write("# Family: " .. family .. "\n")
    f:write("# Generated by calibrate_creaturebar v" .. VERSION .. "\n\n")

    for part, ranks in pairs(data) do
        for rank, coord in pairs(ranks) do
            f:write(part .. "." .. rank .. ".x = " .. tostring(coord.x or 0) .. "\n")
            f:write(part .. "." .. rank .. ".y = " .. tostring(coord.y or 0) .. "\n")
        end
    end

    f:close()
    echo("Saved config: " .. filepath)
end

--- Load coordinate config for a family
local function load_config(family)
    local filepath = SILHOUETTE_CONFIG_DIR .. "/" .. family .. ".cfg"
    local f = io.open(filepath, "r")
    if not f then return {} end

    local data = {}
    for line in f:lines() do
        if not line:match("^#") and not line:match("^%s*$") then
            local part, rank, axis, value = line:match("^(%w+)%.(%d+)%.([xy])%s*=%s*([%-]?%d+)")
            if part and rank and axis and value then
                if not data[part] then data[part] = {} end
                rank = tonumber(rank)
                if not data[part][rank] then data[part][rank] = { x = 0, y = 0 } end
                data[part][rank][axis] = tonumber(value)
            end
        end
    end

    f:close()
    return data
end

--- List available families from silhouette directory
local function scan_families()
    ensure_dir(SILHOUETTE_DIR)
    families = { "default" }

    -- In a full implementation, scan subdirectories of SILHOUETTE_DIR
    -- For now, check for config files
    ensure_dir(SILHOUETTE_CONFIG_DIR)

    local handle = io.popen('ls "' .. SILHOUETTE_CONFIG_DIR .. '" 2>/dev/null')
    if handle then
        for filename in handle:lines() do
            local family = filename:match("^(.+)%.cfg$")
            if family and family ~= "default" then
                local found = false
                for _, f in ipairs(families) do
                    if f == family then found = true; break end
                end
                if not found then families[#families+1] = family end
            end
        end
        handle:close()
    end
end

--------------------------------------------------------------------------------
-- Terminal-based calibration interface
--------------------------------------------------------------------------------

local function display_status()
    local part = BODY_PARTS[current_part_index]
    local family_data = coordinates[current_family] or {}
    local part_data = family_data[part] or {}
    local rank_data = part_data[current_rank] or { x = 0, y = 0 }

    respond("\n=== CreatureBar Calibrator v" .. VERSION .. " ===")
    respond("Family:    " .. current_family)
    respond("Body Part: " .. part .. " (" .. current_part_index .. "/" .. #BODY_PARTS .. ")")
    respond("Rank:      " .. current_rank)
    respond("Position:  x=" .. rank_data.x .. " y=" .. rank_data.y)
    respond("")
    respond("Commands:")
    respond("  ;calibrate set <x> <y>    — set coordinates for current part/rank")
    respond("  ;calibrate next           — next body part")
    respond("  ;calibrate prev           — previous body part")
    respond("  ;calibrate rank <1-3>     — set wound rank")
    respond("  ;calibrate family <name>  — switch family")
    respond("  ;calibrate list           — list all coordinates")
    respond("  ;calibrate copy           — copy current rank to all ranks")
    respond("  ;calibrate save           — save current family config")
    respond("  ;calibrate load           — reload from file")
    respond("  ;calibrate families       — list available families")
    respond("  ;calibrate done           — save and exit")
    respond("===========================================\n")
end

local function set_coordinate(x, y)
    local part = BODY_PARTS[current_part_index]
    if not coordinates[current_family] then coordinates[current_family] = {} end
    if not coordinates[current_family][part] then coordinates[current_family][part] = {} end
    coordinates[current_family][part][current_rank] = { x = x, y = y }
    echo("Set " .. part .. " rank " .. current_rank .. " to x=" .. x .. " y=" .. y)
end

local function copy_to_all_ranks()
    local part = BODY_PARTS[current_part_index]
    local family_data = coordinates[current_family] or {}
    local part_data = family_data[part] or {}
    local source = part_data[current_rank] or { x = 0, y = 0 }

    for _, rank in ipairs(WOUND_RANKS) do
        if not coordinates[current_family] then coordinates[current_family] = {} end
        if not coordinates[current_family][part] then coordinates[current_family][part] = {} end
        coordinates[current_family][part][rank] = { x = source.x, y = source.y }
    end

    echo("Copied " .. part .. " rank " .. current_rank .. " coordinates to all ranks")
end

local function list_all()
    local family_data = coordinates[current_family] or {}
    respond("\n--- " .. current_family .. " coordinates ---")
    for _, part in ipairs(BODY_PARTS) do
        local part_data = family_data[part] or {}
        local line = "  " .. part .. ":"
        for _, rank in ipairs(WOUND_RANKS) do
            local c = part_data[rank] or { x = 0, y = 0 }
            line = line .. string.format("  R%d(%d,%d)", rank, c.x, c.y)
        end
        respond(line)
    end
    respond("---\n")
end

--------------------------------------------------------------------------------
-- Command processing
--------------------------------------------------------------------------------

local function process_command(cmd)
    cmd = cmd:match("^%s*(.-)%s*$") or ""

    if cmd == "" or cmd == "status" then
        display_status()
    elseif cmd == "next" then
        current_part_index = current_part_index + 1
        if current_part_index > #BODY_PARTS then current_part_index = 1 end
        display_status()
    elseif cmd == "prev" then
        current_part_index = current_part_index - 1
        if current_part_index < 1 then current_part_index = #BODY_PARTS end
        display_status()
    elseif cmd:match("^rank%s+(%d+)$") then
        local r = tonumber(cmd:match("^rank%s+(%d+)$"))
        if r >= 1 and r <= 3 then
            current_rank = r
            display_status()
        else
            echo("Rank must be 1, 2, or 3")
        end
    elseif cmd:match("^set%s+(%-?%d+)%s+(%-?%d+)$") then
        local x, y = cmd:match("^set%s+(%-?%d+)%s+(%-?%d+)$")
        set_coordinate(tonumber(x), tonumber(y))
    elseif cmd:match("^family%s+(%S+)$") then
        local fam = cmd:match("^family%s+(%S+)$")
        current_family = fam
        if not coordinates[fam] then
            coordinates[fam] = load_config(fam)
        end
        echo("Switched to family: " .. fam)
        display_status()
    elseif cmd == "families" then
        scan_families()
        echo("Available families: " .. table.concat(families, ", "))
    elseif cmd == "list" then
        list_all()
    elseif cmd == "copy" then
        copy_to_all_ranks()
    elseif cmd == "save" then
        save_config(current_family, coordinates[current_family] or {})
    elseif cmd == "load" then
        coordinates[current_family] = load_config(current_family)
        echo("Loaded config for " .. current_family)
        display_status()
    elseif cmd == "done" then
        save_config(current_family, coordinates[current_family] or {})
        echo("Calibration complete. Config saved.")
        return true -- signal to exit
    elseif cmd == "help" then
        display_status()
    else
        echo("Unknown calibration command: " .. cmd)
    end

    return false
end

--------------------------------------------------------------------------------
-- Upstream hook for ;calibrate commands
--------------------------------------------------------------------------------

local running = true

local function on_upstream(line)
    local cmd = line:match("^;calibrate%s*(.*)")
    if not cmd then cmd = line:match("^;cal%s*(.*)") end
    if cmd then
        local done = process_command(cmd)
        if done then running = false end
        return nil
    end
    return line
end

UpstreamHook.add("calibrate_creaturebar", on_upstream)
Script.at_exit(function() UpstreamHook.remove("calibrate_creaturebar") end)

--------------------------------------------------------------------------------
-- Main
--------------------------------------------------------------------------------

ensure_dir(CONFIG_DIR)
ensure_dir(SILHOUETTE_DIR)
ensure_dir(SILHOUETTE_CONFIG_DIR)
scan_families()

-- Load default family
coordinates["default"] = load_config("default")

-- Handle command-line args
local input = Script.vars[1] or ""
if input:match("help") or input:match("%?") then
    display_status()
else
    echo("CreatureBar Calibrator v" .. VERSION)
    echo("Type ;calibrate or ;cal to interact")
    display_status()
end

-- Keep script alive for interactive use
while running do
    pause(1)
end
