--- @revenant-script
--- name: rofl_questions
--- version: 1.5
--- author: Kragdruk
--- contributors: Alastir, Nodyre, Jahadeem, Soliere
--- game: gs
--- description: Automatically answers Rings of Lumnis trivia questions
--- tags: festival,RoL,Rings,trivia
---
--- Changelog (from Lich5):
---   v1.5 - Rubocop cleanup and removal of duplicate question/answers
---   v1.4 - Updated to include all known questions from Planar, Spiritual, Elemental, Order, and Chaos Rings
---   v1.3 - Updated to include all currently known questions from other scripts and various sources
---   v1.2 - support Arkati or lesser spirit forms of Zelia question
---   v1.1 - fixed patchwork flesh monstrosity answer
---   v1.0 - initial release after 2018 event

-- Question/answer database: { pattern, answer }
local qa = {
    { [[Which lesser spirit says, "For your transgressions, there shall be no shelter for you anywhere that the Mother's eye sees%.%.%."]],  "Aeia" },
    { [[This Tehir%-crafted dye is created from a root found only in the Sea of Fire%.  What is the name of the color%?]],  "ahmdir blue" },
    { [[Suppliers of metals to other bloodlines, this group of burghals often lurk around dwarven caverns, hoping to glean information about the metals trades%.]],  "aledotter" },
    { [[gives you the peace to bear it%.]],  "alexandrite" },
    { [[This metal is primarily found in decorative weapons as it is mildly frail%.  It can be found in green or violet colors%.]],  "Alexandrite" },
    { [[What stem is best recommended when someone has gone for your jugular%?]],  "Aloeas" },
    { [[Which flower, also known as madwort, was adopted by a Sheruvian cult as their sigil%?]],  "Alyssum" },
    { [[The shrine to which lesser spirit lies beyond the rolaren gate in Icemule Trace%?]],  "Amasalen" },
    { [[Which Lesser Spirit is the patron of sacrifice%?]],  "Amasalen" },
    { [[Which lesser spirit says, "For your transgressions, your blood will flow from your body in rivers!"]],  "Amasalen" },
    { [[Give sobriety an _____________ to avoid disaster%.]],  "amethyst" },
    { [[This Arkati's symbol is a black cat's head%.]],  "andelas" },
    { [[This unique blend of silk and thread%-of%-vaalorn prized by House Vaalor for its strength and shimmering appearance%.  What is the name of this fabric%?]],  "Aqilorn" },
    { [[Which lesser spirit favors insects with eight legs%?]],  "arachne" },
    { [[Which lesser spirit says, "For your transgressions, disfiguring venom shall pour through your veins%."]],  "arachne" },
    { [[What is the first name of the founder of House Vaalor%?]],  "Aradhul" },
    { [[The Horse War was a conflict waged between halflings and which elven House%?]],  "Ardenai" },
    { [[This Great Elemental of Fire claims Teras Isle as his abode%.]],  "avregol" },
    { [[This crystal is a primary ingredient in a minor health potion%.]],  "ayanad" },
    { [[What is the Aelotian word for day%?]],  "ayd" },
    { [[What is the name of the proprietor of Pinefar Trading Post%?]],  "belle" },
    { [[Who is the proprietor of the Bare Essentals store in Icemule Trace%?]],  "berrytoe" },
    { [[What is the first name of the founder of House Ashrim%?]],  "Bhoreas" },
    { [[This black metal is a rare variant of its base metal%.  It is said that this metal holds a magical curse and can come in a pure or impure variety%.]],  "black ora" },
    { [[What species of spider bit Arachne on the lip%?]],  "black widow" },
    { [[Which blossom is well%-known as the flower of maidens%?]],  "blaestonberry" },
    { [[What precious gemstone, native to elven lands, is famed for its distinctive inner light, whose waxing and waning is attributed to local mana flows%?]],  "Blazestar" },
    { [[The Earldom of Estoria in the Turamzzyrian Empire has a crest that displays a white horse clenching a black rose in its teeth%.  What is the background color of this crest%?]],  "blue" },
    { [[Found only in Zul Logoth, the powdered version of this stone that from different angles appears all of black, blue, and white, is used as an alchemy component%.]],  "Bluerock" },
    { [[What dwarven clan founded the town of Kharam Dzu%?]],  "Borthuum" },
    { [[Which species of rolton is reputed to have even killed a lord or two%?]],  "Bresnahanini" },
    { [[What potion does nothing for headaches, but much for head mutilations%?]],  "Brostheras" },
    { [[Which halfling culture would be most likely to take up residence near bodies of water%?]],  "Brughan" },
    { [[What hyphenated potion is the enemy of fashionable one%-eyed pirates everywhere%?]],  "Bur-clover" },
    { [[What easily foraged spine will spirit away those unsightly scars on hands and limbs%?]],  "Cactacae" },
    { [[What fruit will unmangle that once broken limb%?]],  "calamia" },
    { [[This animated item will follow its owner around and aid alchemists in their trade%.]],  "Cauldron" },
    { [[Which Arkati watches over the seas%?]],  "Charl" },
    { [[Which Arkati favors the performing arts and has a vast sense of humor%?]],  "Cholen" },
    { [[This group of time travelers will often steal your hard%-earned silvers as payment for your rental of a popular gold item%.]],  "Chronomages" },
    { [[What is the rumored name of Andelas' avatar%?]],  "Claw of Andelas" },
    { [[What gem can be found by plunging your hand into a dead ice elemental%?]],  "clear blue gem" },
    { [[What does the wishing well's plaque in Cysaegir claim to require for your heart's desires%?]],  "coins" },
    { [[What extremely rare metal, known for its sentient properties, has been known to bond with its owner when in weapon form%?]],  "Coraesine" },
    { [[Symbol of _______, known to members of the Order of Voln, helps members combat sheer fear%.]],  "courage" },
    { [[What is the Aelotian word for sun%?]],  "Cyr" },
    { [[What Paladin%-gifted spell helps combat the effects of sheer fear on adventurers%?]],  "Dauntless" },
    { [[Seareach's crest displays a red eagle before a golden sun%.  What is the background color of this crest%?]],  "deep blue" },
    { [[Which climate would primarily be found in the Sea of Fire or the Southron Wastelands%?]],  "Desert" },
    { [[Who was the first mortal responsible for creating the first of the Undead]],  "Despana" },
    { [[What was the name of Despana's undead general%?]],  "dharthiir" },
    { [[So too of black _____________ for you'll despair%.]],  "diopside" },
    { [[This annual forest gnome celebration, held on the first day of Imaeresta, celebrates whose birthday%?]],  "Doneagil Basingstoke" },
    { [[This metal is found in white veins with crimson specks%.  It is generally found near long%-dormant volcanoes and when whisked through the air, glows an angry red%.]],  "Drakar" },
    { [[What is the traditional agate used for the Surath Dai%?]],  "drought" },
    { [[What is the Aelotian word for two%?]],  "Dyo" },
    { [[What is the name of the only non%-corporeal entity to haunt Bonespear Tower%?]],  "eidolon" },
    { [[The Temple of Wisdom was dedicated in the year 1000 Erithian as a millenial celebration to the founding of what city on Atan Irith%?]],  "Eloth-Ra" },
    { [[I am the God of Craftsmanship, the Master of the Forge%.  Who am I%?]],  "Eonak" },
    { [[This Arkati's symbol is a golden anvil%.]],  "eonak" },
    { [[Who is the consort of Imaera%?]],  "Eonak" },
    { [[This metal can be found in a brilliant white or silver hue%.  Considered a high honor to wield amongst dwarven clansman, this metal is sanctified in the hands of a holy warrior%.]],  "eonake" },
    { [[This Arkati's symbol is red, stylized flames%.]],  "Eorgina" },
    { [[Which Arkati styles herself the Queen of the Gods%?]],  "Eorgina" },
    { [[Which Arkati's symbol burns against an ashen background%?]],  "Eorgina" },
    { [[Which elven group unleashed a secret magic upon Despana during the battle at Maelshyve%?]],  "Faendryl" },
    { [[This light green, dark veined metal was often found in caverns in forests dubbed "_____ Pockets"%.]],  "Faenor" },
    { [[What Plane 4 paladins regenerate quickly unless you slay them quicker%?]],  "fallen crusader" },
    { [[This creature follows around his or her wizardly master%.]],  "familiar" },
    { [[The Nalfein are known to engage in a complicated method of discreet communication with what innocuous prop%?]],  "Fan" },
    { [[But _____________ is disaster's prediction%.]],  "firestone" },
    { [[The Barony of Bourth in the Turamzzyrian Empire has three black yew trees on a field of white that is ringed by hawk feathers%.  How many hawk feathers form the ring%?]],  "Five" },
    { [[What hunting ground near Icemule Trace is overun with undead plants]],  "frozen bramble" },
    { [[Which lesser spirit manifested recently on an island in The Abandoned Waters%?]],  "Ghezresh" },
    { [[Which lesser spirit says, "You shall now forever stand in the shadow of your allies%."]],  "Ghezresh" },
    { [[This recently discovered metal can only be found near active and violent undersea volcanos%.]],  "ghezyte" },
    { [[The Arkati L'Naere was also known as]],  "giver of life" },
    { [[Of bronze, ghezyte, glaes, and vultite, which material is not metallic%?]],  "Glaes" },
    { [[This metal is mildly translucent and dark, and it is formed around the atmosphere of a volcano%.]],  "Glaes" },
    { [[What material is said to have been all together absent from the aelotoi's world of Bre'Naere%?]],  "glaes" },
    { [[Krolvin settlement northwest of Wehnimer's Landing]],  "Glaoveln or Isle of Glaoveln" },
    { [[What ancient tree is housed inside of the gardens of Veythorne Manor%?]],  "glowbark" },
    { [[What is the name of the ritual performed when a Brughan child reaches a certain age%?]],  "goating" },
    { [[What device is used to notify the town when Teras is in danger%?]],  "gong" },
    { [[I am the Goddess of Death, and the Mistress of Eternity%.  Who am I%?]],  "Gosaena" },
    { [[This Arkati's symbol is a silver or grey sickle%.]],  "Gosaena" },
    { [[The Barony of Dragach in the Turamzzyrian Empire has a crest displaying a red bighorn ram facing right before white mountains%.  What is the background color of this crest%?]],  "Green" },
    { [[Mashed alligator lily will make what color dye%?]],  "Grey" },
    { [[What is the Aelotian word for family%?]],  "gyrrdha" },
    { [[The feather of what bird, braided into one's hair, shows disagreement with Chaston's Edict%?]],  "hawk" },
    { [[This exotic and extremely rare metal is said to be the bane of extraplanar creatures%.  It is also said only the most skilled adventurers can wield this metal%.]],  "high steel" },
    { [[This garment, worn over the forehead to cover his or her ear tips, is worn by both male and female forest gnomes when at war%.]],  "huiteo" },
    { [[Which lesser spirit says, "For your transgressions, all those with cause against you shall have the strength of a hundred men apiece%."]],  "Huntress" },
    { [[This son of Meyno is said to have turned the creatures of Stone Valley hostile and warlike%.]],  "Illoke" },
    { [[Who turned the stone giants and other stone creatures of Stone Valley hostile%?]],  "Illoke" },
    { [[Which Arkati is typically honored by autumnal festivals%?]],  "Imaera" },
    { [[This silver, tinted blue or gold metal is considered one of the most beautiful metals%.]],  "imflass" },
    { [[What's the grey metal used by blacksmiths%?]],  "iron" },
    { [[What clan does the Rakan Family belong to%?]],  "Issimir Ogre Clan" },
    { [[Which giantkin Clan would be most suited toward the lifestyle of a merchant%?]],  "Issimir Ogre Clan" },
    { [[This Arkati's symbol is a stylized, green wisp of smoke%.]],  "Ivas" },
    { [[Who is the only Arkati who will speak to Gosaena%?]],  "Jastev" },
    { [[Who is the caretaker of the Four Winds%?]],  "Jaston" },
    { [[Which Arkati has all rights to boast about his incredible skill at arms%?]],  "Kai" },
    { [[Which tree has been given the nickname of "bloodleaf" trees%?]],  "kakore" },
    { [[This son of Meyno fled from his brother after he staged a coup that saw his mother entombed in the ground%.]],  "Khaarne" },
    { [[Who is the eldest son of Meyno%?]],  "Khaarne" },
    { [[Name the specific term a halfling would use to refer to the walls of his ger%.]],  "Khana" },
    { [[Which Arkati is believed by some commoners to be the last of the Drakes%?]],  "Koar" },
    { [[Who is the only Arkati to beat Kai in armed combat]],  "Koar" },
    { [[Who was the first Patriarch of House Faendryl%?]],  "Korthyr Faendryl" },
    { [[What creature native to the environs of Wehnimer's Landing requires a blunt weapon to skin%?]],  "krag dweller" },
    { [[This silver%-hued metal is extremely rare and usually found deep in ancient craters masked by the growing landscape%.]],  "Krodera" },
    { [[Which lesser spirit says, "For your transgressions, the plants of the world shall give you neither comfort nor shelter%."]],  "Kuon" },
    { [[Which lesser spirit would be most at home in a field of herbs and flowers%?]],  "Kuon" },
    { [[Who suggested, in the wake of the Ur%-Daemon War, that Imaera grant healing properties to certain plants so mortals could more easily help themselves%?]],  "Kuon" },
    { [[Which Arkati was considered a traitor and a renegade by her peers%?]],  "l'naere" },
    { [[Which lesser spirit says, "For your trangressions, all those you love will be parted from you, never to join you again%."]],  "Laethe" },
    { [[The Barony of Highmount in the Turamzzyrian Empire has a crest that displays a white bear in manacles on a field of red%.  Which way is the bear facing%?]],  "left" },
    { [[The County of Allace in the Turamzzyrian Empire has a crest that displays a white seagull with widespread wings on a field of dark blue%.  Which way is the seagull facing%?]],  "left" },
    { [[Which lesser spirit says, "For your transgressions, the hands of all honorable people will turn against you, leaving you surrounded by traitors and fools%."]],  "Leya" },
    { [[Which Pantheon is considered "good" or "light"]],  "Liabo" },
    { [[What apex undead master comes in cool and hot varieties%?]],  "Lich" },
    { [[Soul golems have the eerie ability to remove what preservation spelling from the recently fallen%?]],  "Lifekeep" },
    { [[What is the first name of the founder of House Illistim%?]],  "Linsandrych" },
    { [[What is the Aelotian word for sky%?]],  "Lira" },
    { [[What is the first month of the Elanthian calendar%?]],  "Lormesta" },
    { [[Which Arkati is the keeper of the Ebon Gate%?]],  "Lorminstra" },
    { [[Who is the Goddess of Winter%?]],  "Lorminstra" },
    { [[Which Pantheon is considered "evil" or "dark"]],  "lornon" },
    { [[What Rift%-dwelling ghoulies have a talent for fading into the shadows when confronted]],  "lost soul" },
    { [[Who do the Erithi revere as the Light God of Knowledge%?]],  "Lumnis" },
    { [[Which Arkati is the wife of Koar%?]],  "lumnis" },
    { [[Which Arkati prefers lies over truth%?]],  "Luukos" },
    { [[Cholen is to music, as Tarandel is to]],  "Lyrics" },
    { [[Which Arkati was the first victim of the Sorrow of the World]],  "Maigra" },
    { [[Found along the Vornavian Coast, this creature is part%-man, part%-scorpion%.]],  "manticore" },
    { [[This Arkati's symbol is a star of six black tentacles%.]],  "Marlu" },
    { [[Which Arkati is believed by many to be an Ur%-Daemon%?]],  "Marlu" },
    { [[This elven outcast would eventually bring magical teaching to the nomadic halfling tribes%.]],  "Memailly" },
    { [[What is the Aelotoi word for forever%?]],  "Meril" },
    { [[Who is the matriarch of the stone giant tribes%?]],  "Meyno" },
    { [[Question was about the dwarven earth ship last seen in EG05 and what it was known as]],  "Mithril Juggernaut" },
    { [[What is the name of the dwarven scholar turned lunatic that is housed in the Teras Asylum%?]],  "Moblak" },
    { [[Which Arkati finds comfort in suffering and torture%?]],  "Mularos" },
    { [[What thrice%-named Scatter citizen will lash at you with scythe%-like hands]],  "murky soul siphon" },
    { [[What is the Aelotian word for six%?]],  "Myn" },
    { [[What Rift%-dwelling n'er%-do%-wells enjoy a good tackle%?]],  "n'ecare" },
    { [[What is the traditional agate used for the Nathala Dai%?]],  "Nathala" },
    { [[What is the name of the recently discovered abandoned temple outside Fhorian Village%?]],  "nelemar" },
    { [[Which Pantheon is considered neither "evil" nor "good"]],  "Neutrality" },
    { [[Which creature might you run into if you jump off a high ledge that leaves you prone and stunned upon landing%?]],  "night hound" },
    { [[I am the Patroness of water, sailors, and sea life%.  Who am I%?]],  "Niima" },
    { [[Which lesser spirit rides with the dolphins%?]],  "Niima" },
    { [[Which lesser spirit says, "For your transgressions, the water you seek to drink will be as dust, and the water you seek to escape will overwhelm you%."]],  "niima" },
    { [[The Earldom of South Hendor is in which part of the Turamzzyrian Empire%?]],  "North" },
    { [[Descriptions of undermining tricksters and merry pranksters are commonly associated with this bloodline%.]],  "Nylem" },
    { [[The center of Briarstone Court in Ta'Illistim is marked by what monument%?]],  "obelisk" },
    { [[Which lesser spirit says, "For your transgressions, a contract has been placed against you%."]],  "Onar" },
    { [[Which Lesser Spirit works from the shadows, most often at the behest of Eorgina%?]],  "Onar" },
    { [[Which Spirit was responsible for the crafting of the first blade ever possessed by a mortal%?]],  "Onar" },
    { [[What is the traditional agate used for the Eloth Dai%?]],  "owleye" },
    { [[What aelotian fabric is woven from the hair of the Paeladri goats%?]],  "paeline" },
    { [[What halfling clan founded Icemule Trace%?]],  "paradis" },
    { [[What thrice%-named Sanctum citizen can bring himself back from the dead%?]],  "patchwork flesh monstrosity" },
    { [[In the language of flowers, what does an Elanthian snow rose represent%?]],  "perfection" },
    { [[This Arkati's symbol is a golden sunburst%.]],  "Phoen" },
    { [[Battles against liches will take their toll if you fail to smash this "what" holding their soul%?]],  "phylactery" },
    { [[What grass will staunch that abdominal accident%?]],  "Pothinir" },
    { [[Mashed wood violet will make what color dye%?]],  "Purple" },
    { [[What is the Aelotian word for seven%?]],  "quen" },
    { [[Which Arkati is believed to be unable to be together in the same place as Phoen%?]],  "Ronan" },
    { [[What is the Aelotian word for five%?]],  "ruet" },
    { [[Once a home for the wizard Kiergaunt Pandarre, this demolished area]],  "Ruined Tower" },
    { [[This elite elven military unit, led by Taki Rassien Vaalor, was utterly destroyed at the Battle of ShadowGuard%.]],  "Sabrar" },
    { [[What rare variety of bloodjewel borrows its name from a dukedom of the Turamzzyrian Empire%?]],  "Selanthan" },
    { [[Where can you find ghostly pookas, shadow mares, shadow steeds, and night mares%?]],  "shadow valley" },
    { [[What spooky Sanctum citizen will make you more than sick with his projectile vomiting%?]],  "shambling lurk" },
    { [[What is the poorest section of Wehnimer's Landing%?]],  "shanty town" },
    { [[What is the first name of the founder of House Ardenai%?]],  "Sharyth" },
    { [[What is the name of the phenomenon that adventurers feel when facing an undead creature that is more powerful than he]],  "sheer fear" },
    { [[Which Arkati is constantly in conflict with Ronan over ownership of the night and sleep%?]],  "Sheru" },
    { [[Which Arkati longs to take residence in your nightmares%?]],  "Sheru" },
    { [[Most often found in shades of orange or crimson, this lantern%-shaped flower]],  "Sirenflower" },
    { [[Which flower is believed to have come not from the hand of Imaera but from the hand of Jastev%?]],  "sirenflower" },
    { [[Powdered white pearl, nightbloom blossom, and a what will make greater repelling oil%?]],  "small dandelion" },
    { [[This fearsome blade was found by halflings and eventually placed into the care of the Arkati Kai%.]],  "Soulingen" },
    { [[What limb%-restoring clove also lends its name to one of the Cooperative Houses of Elanthia%?]],  "Sovyn" },
    { [[What ghostly Nelemar native is just as deadly with a harpoon as a hatchet]],  "spectral triton defender" },
    { [[The Elemental Confluence produces what kind of blossom in its environs%?]],  "spiky luminescent blossom" },
    { [[What is the traditional agate used for the Tichan Dai%?]],  "Storm" },
    { [[Which climate would primarily be found in Kharam Dzu or River's Rest%?]],  "Subtropical" },
    { [[What is the traditional agate used for the Yachan Dai%?]],  "Summer" },
    { [[What root is used as a special washing treatment in the process used to create ramie silk and linen%?]],  "Talneo" },
    { [[Which Arkati is the dead triplet of Cholen and Jastev%?]],  "Tarandel" },
    { [[These nomadic humans are accustomed to the harsh conditions of the desert%.]],  "Tehir" },
    { [[Unearthly priestesses eternally wander which temple in the Landing%?]],  "temple of love" },
    { [[What area is monkeyflower native to%?]],  "Teras Isle" },
    { [[This annual Malghavian%-hosted event during the month of Lumnea, is predominately a showcase for combat skill competitions%.]],  "The Trine" },
    { [[This bantam wizard lends his name to a very powerful ward%.]],  "thurfel" },
    { [[What is the name of the musician who was elevated to the status of a Lesser Spirit when he finished his performance for the Lord of Song%?]],  "Tilamaire" },
    { [[Which lesser spirit says, "For your transgressions, all music of this world will fall upon your accursed ear]],  "Tilamaire" },
    { [[What is the name for the traditional robe with an hourglass%-shaped backpiece worn by many aelotoi%?]],  "Toqua" },
    { [[What leaf will ensure you stop slurring your words%?]],  "torban" },
    { [[Which County of the Turamzzyrian Empire has a crest of a white stork on a field of light blue%?]],  "Torre" },
    { [[What structure on Ghorsa Isle stands watch%?]],  "tower" },
    { [[In Karazja Jungle, this creature lurks in trees and makes combat difficult for melee adventurers]],  "tree viper" },
    { [[a trilliant%-cut gem, a tri%-stranded chain, and an elaborate metal setting%.  What is the name of this item%?]],  "Trinette" },
    { [[What is the black symbol in the center of the gold and red crest of the Barony of Jantalar of the Turamzzyrian Empire%?]],  "Triskelion" },
    { [[Some believe that Marlu is actually what interplanar beast]],  "Ur-Daemon" },
    { [[This Arkati's symbol is a black scimitar%.]],  "V'tull" },
    { [[This blue or white metal was named after the elves who first discovered it%.]],  "vaalorn" },
    { [[What sorcerous Rift%-dwellers are happy to give you a ride back to Icemule in a million little pieces%?]],  "Vaespilon" },
    { [[Song of ______ creates an aura of protection around adventurers and is known to combat sheer fear%.]],  "Valor" },
    { [[What is the name of the erithian side%-tied waist sash made from elaborately folded cloth%?]],  "Vatanura" },
    { [[This black, blue speckled metal is one of the most rare metals around%.  It can be found within large meteors that have fallen from the sky%.]],  "Veil iron" },
    { [[Where are the remnants of ancient ruins located in Cysaegir%?]],  "Vista Knoll" },
    { [[Which lesser spirit says, "For your transgressions, all those you love will be parted from you%."]],  "Voaris" },
    { [[Which lesser spirit says, "For your transgressions, no punishment could be greater than that which you bring upon yourself%."]],  "Voln" },
    { [[This blue with silver veined metal is one of the most commonly traded metals around Elanthia%.]],  "Vultite" },
    { [[What is the only profession able to be formally acknowledged as a T'Kirem Bear Clan member%.]],  "Warrior" },
    { [[Ground valerian root will make what color dye%?]],  "white" },
    { [[What color are the petals carried by the pretty flower girl in the Landing%?]],  "white" },
    { [[What variety of trees create a beckoning shelter in Linsandrych Common%?]],  "Willow" },
    { [[Which flower was once an anemone transformed by Jaston%?]],  "windflower" },
    { [[What potion will help when you've taken a lot more than a punch in the gut%?]],  "Wingstem" },
    { [[This medium%-sized shrub bears showy red berries and is indigenous to the snowy region of Icemule%.]],  "winterberry" },
    { [[Which small fruit is celebrated once a year in River's Rest%?]],  "winterberry" },
    { [[Toullaire was utterly destroyed in 4593 in a magical catastrophe, creating the magically%-ravaged wasteland, commonly referred to as what%?]],  "Wizardwaste" },
    { [[What lichen will tame your muscle twitches, but leave your speech slurred%?]],  "Wolifrew" },
    { [[In tune with nature, which giantkin Clan lives a secluded life deep within the DragonSpine Mountains%?]],  "Wsalamir" },
    { [[Which shop in Icemule Trace only sells one item%?]],  "Wurt's Amulets" },
    { [[The Barony of Bourth claims what massive forest%?]],  "Wyrdeep" },
    { [[What is the name for the typical low%-heeled shoes with gently pointed toes worn by erithians%?]],  "Yatane" },
    { [[What is the Aelotian casual word for wind%?]],  "Yllyc" },
    { [[Commonly assumed to be insane, this goddess of the moons is symbolized by a silver crescent moon upon a field of black%.]],  "Zelia" },
    { [[This Arkati is often accused of being insane%.]],  "Zelia" },
    { [[This lesser spirit is often accused of being insane%.]],  "zelia" },
    { [[Which Arkati is thought to have caused larkspur to grow in meadows where she danced]],  "Zelia" },
    { [[Which of the Arkati considers freedom from lucidity to be the greatest freedom that can be achieved%?]],  "zelia" },
    { [[Closest to storm clouds, this metal is primarily found atop high mountain peaks%.]],  "zorchar" },
    { [[Which dwarven city has a prankster canary that roams the streets%?]],  "Zul Logoth" },
    { [[What is the Aelotian word for ten%?]],  "Zyel" },
    { [[Which direction in the sphere leads to the third plane in the Rift]],  "east" },
    { [[Which direction in the sphere leads to the second parallax in the Rift]],  "west" },
    { [[What was the name of the sickness the dwarves brought home from the Undead War%?]],  "Red Rot" },
    { [[Whose first action as Patriarch of the Faendryl was to have his own mother executed%?]],  "Yshryth Silvius Faendryl" },
    { [[Under Faendryl law, where must summoners that tap into new valences and find new demons report their findings%?]],  "Enchiridion Valentia" },
    { [[What was the name of the peak where the dwarves and giantmen settled their war%?]],  "Sunfist" },
    { [[What is the name of the capital city of Aldora%?]],  "Elstreth" },
    { [[What is the name of the griffin%-owning wizard who has hosted adventurers at his spire]],  "Sylinar" },
    { [[Which famous elf was the wielder of the legendary veil iron sword, "Aramier"]],  "Taki Rassien" },
    { [[A survivor of Maelshyve, this warrior said of The Undead War, "%.%.%.nothing could ready a dwarf for the banshee%."]],  "Rhak" },
    { [[What is the Grot'Karesh Hammer Clan word that means "wanderer]],  "Ishan" },
    { [[What was the given name of the founder of Wehnimer's Landing%?]],  "Rone" },
    { [[Hearthstone Manor was built by whom%?]],  "Kerrington Ravenhearth" },
    { [[What county is River's Rest in%?]],  "Torre" },
    { [[What are the small traveling bands of the Issimir Ogre Clan called%?]],  "kegritsha" },
    { [[This massive book of law, compiled by Emperor Perrinor in 4694, serves as the basis for the Turamzzyrian legal system]],  "Rysus Codex" },
    { [[What town's name loosely translates to "turtle's egg" in trollish%?]],  "River's Rest" },
    { [[What is the name of the Krolvin Settlement located northwest of Wehnimer's Landing%?]],  "Isle of Glaoveln" },
    { [[Who are the temporal wizards who claim ownership]],  "Chronomages" },
    { [[What is the name of the leader of a Krolvin War Fleet%?]],  "Czag Dubra" },
    { [[This legendary greataxe, wielded by the martyred Grandmaster Allasander]],  "Spiritcry" },
    { [[Who led the Laurentiu Faction against the supposed "false Patriarch" of the Faendryl%?]],  "Qhwinn Laurentiu Faendryl" },
    { [[What is the first name of the guard who fancies Helga's stew%?]],  "Quin" },
    { [[In what year did a cataclysm strike River's Rest, causing the creation of the Tempest Falls%?]],  "5018" },
    { [[What is the haunted village that, for many years, hosted the Ebon Gate festival%?]],  "Velathae" },
    { [[This constellation of 5 stars is said to belong to Eonak%.]],  "The Hammer" },
    { [[What is Quin Telaren's nickname%?]],  "Sleepy" },
    { [[Wehnimer's Landing receives grain, produce, and steel, from which Northern Province%?]],  "Jantalar" },
    { [[At the end of the Age of Chaos, what newly formed giantkin clan helped to rebuild the walls of Ta'Vaalor%?]],  "Issimir Ogre Clan" },
    { [[Twenty one stars shine brightly in The First, a constellation that represents which Drake%?]],  "Ka'lethas" },
    { [[Which Elven Nation is known as home to excellent hunters%?]],  "Ta'Ardenai" },
    { [[Rajin Maeramil, the founder of the Wind Runner Clan, died fighting what group]],  "krolvin slavers" },
    { [[What pyramid%-shaped structure sits at the heart of Old Ta'Faendryl%?]],  "Basilica" },
    { [[What is the name of the island that hosted the most recent Ebon Gate festival%?]],  "Caligos Isle" },
    { [[Which seafaring Elven Nation perished in the events known as the Sea Elf War%?]],  "Ta'Ashrim" },
    { [[What was the name of the Faendryl girl whose death was the catalyst of the war between the dark elves and sea elves%?]],  "Chesylcha" },
    { [[The Sisters of the Hidden Eye, famed for their ability to divine the future, could be hired in what city%?]],  "Phannus" },
    { [[Which clan has a tribe that refers to themselves as Highmen%?]],  "T'Kirem Bear Clan" },
    { [[The constellation known as the Queen of Enlightenment contains five stars, representing which Arkati%?]],  "Lumnis" },
    { [[The final battle of the Undead War took place at what keep%?]],  "Maelshyve" },
    { [[This one%-time famous armor and weaponsmith now calls River's Rest his permanent home]],  "Hortinger" },
    { [[Which moon has no nicknames%?]],  "Makiri" },
    { [[What sanguine, rat infested village is host to an arena]],  "Bloodriven" },
    { [[What is the name of the burghal gnome vintner below Ta'Vaalor%?]],  "Bezzik" },
    { [[Which Giantkin Clan was formed by outcasts from the T'Kirem and Grishknel Clan]],  "Grot'karesh Hammer Clan" },
    { [[Queen Issyldra the Ice Witch claimed the territory of Hendor during what frigid campaign%?]],  "Witch winter" },
    { [[In 4997, a balloon carrying dwarven explorers crashed on what island%?]],  "Teras" },
    { [[The Grishknel Wolf Clan became information traders with which Elven capital%?]],  "Ta'Nalfein" },
    { [[Finished in 4909, this great wall stretches from the DragonSpine mountains]],  "Demonwall" },
    { [[What is the name of the gnomish dirigible known for hosting merchant festivals%?]],  "Dhu Gillywack" },
    { [[Which old city, located within the borders of the Turamzzyrian Empire, was devastated by a magical calamity]],  "Toullaire" },
    { [[Who runs the armory in the Landing%?]],  "Aznell" },
    { [[Who was the first Matriarch of the Faendryl people%?]],  "Geniselle Anaya Faendryl" },
    { [[Who was the second Matriarch of the Faendryls after Qhwinn Laurentiu Faendryl]],  "Nikasha Pavanti Faendryl" },
    { [[What was the name of the swampland that, for many years, hosted the Ebon Gate festival%?]],  "Feywrot Mire" },
    { [[Name this city which serves as the academic center of the Turamzzyrian Empire%?]],  "Nydds" },
    { [[A Convocation, a Returning, and a Cessation, all occured on a field distinguished by the presence of what rare material%?]],  "Coraesine" },
    { [[Which Giantkin Clan was hunted for almost a century after an incident with a hunter named Templeton Mannelig and a wendigo%?]],  "Wsalamir Arctic Clan" },
    { [[What is the given name of the reigning Turamzzyrian Emperor%?]],  "Aurmont" },
    { [[This constellation of 6 stars is known as Zelia's ladies%-in%-waiting%.]],  "The Handmaidens" },
    { [[What now%-sunk luxury sealiner took adventurers to the Southron Wastes%?]],  "Wavedancer" },
    { [[What was the name of the legendary sword carried by the first ruler of the Turamzzyrian Empire%?]],  "Searswathe" },
    { [[Jantalarian forces reclaimed Doggoroth Keep in 5089, defeating what previous humanoid occupants]],  "orcs" },
    { [[Which war happened approximately 100,000 years ago]],  "Ur-Daemon" },
    { [[What is the name of the toymaker's home where adventurers can build their own demented dolls]],  "Delirium Manor" },
    { [[This traveling dwarven earth ship, last seen in a ghostly form at the 5105 Ebon Gate]],  "mithril juggernaut" },
    { [[Which Elven Nation is surrounded by a moat]],  "Ta'Vaalor" },
    { [[What famous pirate has a statue erected in River's Rest%?]],  "Ketain" },
    { [[Which Patriarch of the Faendryl ordered the Palestra to be founded]],  "Ondreian Shamsiel Faendryl" },
    { [[Name the Dwarven "Revel" famous for its weapon and armorsmiths]],  "anfelt" },
    { [[Name the smallest of the known moons]],  "Makiri" },
    { [[Name the lake that separates the cities of Ta'Illistim and Ta'Vaalor]],  "lake of fear" },
    { [[What sacred area is host to cherished memories and memorials of loved ones passed%?]],  "Halcyon Hills" },
    { [[This Northern Province is well%-known for its honey meads and brown ales%.]],  "Mestanir" },
    { [[Name this powerful necromantic artifact employed by the Horned Cabal]],  "sphere of sorrows" },
    { [[What was the name of the Empire that preceded the Turamzzyrian Empire]],  "Kannalan" },
    { [[Who was the father of demon summoning that was beheaded for not reporting his findings]],  "Thyrsos Kanigel Faendryl" },
    { [[A star for each of three tines, one for the base, and two for the haft comprise the Trident]],  "Charl" },
    { [[Who enslaved the Aelotoi]],  "kiramon" },
    { [[I am the red moon orbiting Liabo%.  What is my name]],  "Tilaok" },
    { [[The sole star Krrska comprises which constellation]],  "The Huntress" },
    { [[Which Elven Nation is known as the "Shining]],  "Ta'Illistim" },
    { [[What awkward avian lends its name]],  "Albatross" },
    { [[Three Wsalamir Arctic Clan warriors survived the battle of Maelshyve]],  "Eahnimaki" },
    { [[What was the full name of the first Empress of Tamzyrr%?]],  "Selantha Anodheles" },
    { [[In what century was the Kingdom of Torre annexed into the Turamzzyrian Empire%?]],  "45th" },
    { [[What Ebon Gate game pits dauber against dauber]],  "ghoul" },
    { [[What is the name of a famous Art Gallery in Ta'Loenthra]],  "Hanesyddol Museum" },
    { [[These crepuscularly fatal weapons and vambraces, always forged of black alloy]],  "shadowdeath" },
    { [[What is the name of the fortress city built, maintained, and magically guarded by the Grot'karesh Hammer Clan]],  "Kilanirij" },
    { [[Which Elven Nation is most renown for its mastery of politics and espionage]],  "Ta'Nalfein" },
    { [[This book, said to be written in the language of the Daemons, was lost shortly after being found by Despana]],  "tormtor" },
    { [[What is the Shattered Continent]],  "archipelago" },
    { [[On the Eve of the Reunion, the citizens of what Turamzzyrian Barony honor the dead of Skyreach]],  "Allace" },
    { [[What giantman clan's members are known for choosing not to speak%?]],  "Wsalamir Arctic Clan" },
    { [[Who do the Erithi revere as the Dark God of Knowledge%?]],  "Fash'lo'nae" },
    { [[What is the Aelotian word for animal%?]],  "faunir" },
    { [[How many interlocking circles of blue are pierced by red arrows]],  "two" },
    { [[While _____________ is the foul spirit that binds us%.]],  "chrysoberyl" },
    { [[But _____________ is an ill%-begotten wish%.]],  "deathstone" },
    { [[What is the traditional agate used for the Valaka Dai%?]],  "beetle" },
    { [[What is the Aelotian word for four%?]],  "ylim" },
    { [[If you referred to a female healer as a "raeni", you are probably of which race%?]],  "Aelotoi" },
    { [[What is the Aelotian word for night%?]],  "suta" },
    { [[The Barony of Vornavis is in which part of the Turamzzyrian Empire%?]],  "Northern" },
    { [[What is the name of female Erithi headwear that is worn in wave%-like peaks flowing back from the forehead%?]],  "atika" },
    { [[This race often lives as servants to elven host families%.]],  "Burghal gnome" },
    { [[Which halfling warrior was able to slip past Krolvin enemies and save Wehnimer's Landing only to die that same day%?]],  "Talbot Dabbings" },
    { [[What is the Aelotian word for dream%?]],  "sutara" },
    { [[This halfling culture suffered a devasting loss when its pony herds were destroyed by the Ardenai elves]],  "Mhoragian" },
    { [[Which Elven house is credited with killing all of the halfling ponies in the Horse War%?]],  "Ardenai" },
    { [[Who wrote, "%.%.%.and then the Mother of Wisdom herself appeared to them in the valley]],  "Ilahan" },
    { [[Elusive and discreet, burghals of this culture never speak publically about their association]],  "Neimhean" },
    { [[What is the only House to be expelled from the Elven Empire%?]],  "Ta'Faendryl" },
    { [[What is the first name of the founder of House Nalfein%?]],  "zishra" },
    { [[What is the Aelotian word for love%?]],  "amin" },
    { [[For many years, the Erithi wandered Elanthia in disguise%.  What were they often mistaken for%?]],  "half-elves" },
    { [[What is the erithian version of a ferroniere%?]],  "elothrai" },
    { [[What giantman clan consistes of primarily warriors%?]],  "T'Kirem Bear Clan" },
    { [[Which Barony of the Turamzzyrian Empire has a crest of a gold crown in a circle of white on a field of red%?]],  "Mestanir" },
    { [[Which giantkin Clan favors rogues and scouts%?]],  "Grishknel Wolf Clan" },
    { [[What is the Aelotian word for nine%?]],  "Aphos" },
    { [[Which Earldom in the Turamzzyrian Empire has a crest of a golden hawk head facing right on a field of Kestrel blue%?]],  "Chastonia" },
    { [[Which Barony of the Turamzzyrian Empire has a crest of a golden sheaf of grain]],  "Oire" },
    { [[What is the name of male Erithi headwear that is worn in wave%-like peaks flowing back from the forehead%?]],  "Atiki" },
    { [[What is the Aelotian word for eight%?]],  "Ymer" },
    { [[Name this famed Loenthran merchant vessel that plies the clouds%?]],  "Ilyan Cloud" },
    { [[What is the first name of the founder of House Loenthra%?]],  "Callisto" },
    { [[What giantman clan is best known for stealth%?]],  "Grishknel Wolf Clan" },
    { [[The Duchy of Selanthia is in which part of the Turamzzyrian Empire%?]],  "western" },
    { [[The Earldom of Honneland is in which part of the Turamzzyrian Empire%?]],  "eastern" },
    { [[The Duchy of Aldora is in which part of the Turamzzyrian Empire%?]],  "southern" },
    { [[Who are the warriors trained to protect Faendryl sorcerers from summoned demons%?]],  "Palestra" },
    { [[Which County has a crest of two black towers on a field of dark green%?]],  "Trauntor" },
    { [[What is the Aelotian word for one%?]],  "Eyr" },
    { [[Which aelotian clan takes pleasure in the idea of owning gems and wearing jewelry%?]],  "Vaer'sah" },
    { [[What is the Aelotian word for three%?]],  "Caswe" },
    { [[The crest of the Barony of Talador in the Turamzzyrian Empire was banned by which nearby Barony's law%?]],  "Jantalar" },
    { [[Lightning elementals have been known to give adventurers nasty shocks when they are struck by what kinds of weapons%?]],  "metallic" },
    { [[What is the name of the trading post located northeast of Icemule Trace%?]],  "pinefar" },
    { [[Which tragic creatures are the twisted result of an experiment involving a bat and elf%?]],  "vesperti" },
    { [[Who is the proprietor of the Bare Essentials store in Icemule Trace%?]],  "berrytoe" },
    { [[Known to cure any one, single dose of poison, what fungus can be scraped from the walls of Czeroth Caverns]],  "ochre-colored" },
    { [[Trained by Jantalarians and then set loose in the outlands near the eastern edges of Solhaven]],  "dobrem" },
    { [[This reptilian carnivore "dune glider," native to the Tehir deserts]],  "Morduska" },
    { [[What is the name of Belle's tragically dead husband%?]],  "ardo" },
    { [[What is the last month of the Elanthian calendar%?]],  "Eorgaen" },
    { [[What is under the bed in a cozy shack in a garden in Wehnimer's Landing%?]],  "housecat" },
    { [[If not knocked down before receiving the final blow, an earth elemental can topple over on adventurers doing what kind of damage%?]],  "crushing" },
    { [[The dais in the Hanging Gardens of Ta'Illistim is ringed by what slender structures%?]],  "columns" },
    { [[This creature sports tentacles instead of claws and is at home in the harsh desert environment%.]],  "qahzumar" },
    { [[Who was the lord of Darkstone Castle%?]],  "Estrion" },
    { [[This reptilian carnivore "sand slider," native to the Tehir deserts]],  "Selshis" },
    { [[What is the name of the archmage that runs Ye Olde Magick Shoppe in the Landing%?]],  "Pherantyr" },
    { [[Where can you find a friendly hound to rest with on Teras%?]],  "golden helm inn" },
    { [[This flying powder%-blue creature is commonly skinned to produce feathers that give lightning flares]],  "storm griffin" },
    { [[What creature, when skinned, has the power to cure one of poison%?]],  "firethorn shoot" },
    { [[What does the gnome barker in Icemule Trace sell%?]],  "snow cones" },
    { [[What objects handsomely decorate the west wall of Old New]],  "shields" },
    { [[What do you get when you break through the rock hard hide of a krag dweller%?]],  "brilliant purple opal" },
    { [[This creature follows around his or her rangerly master%.]],  "companion" },
    { [[Cysaegir was originally which elven town%?]],  "Glimae'den" },
    { [[What type of scrip can be collected in Reim%?]],  "ethereal" },
    { [[The Elemental Confluence produces what kind of root in its environs%?]],  "dense earthen root" },
    { [[The Elemental Confluence produces what kind of stalk in its environs%?]],  "brittle crystalline stalk" },
    { [[Ta'Illistim houses the largest known temple to Mularos and a shrine to which of his priests%?]],  "eryael" },
    { [[This Great Elemental of Water disputes Avregol's claim to Teras Isle]],  "Nelemar" },
    { [[What is the name of the river located north of Icemule, and south of Pinefar%?]],  "olbin" },
    { [[What is the name of the body of water that resides north of the ruins of Ta'Faendryl%?]],  "Lake of Shadowed Sorrows" },
    { [[Passage from Solhaven to the Sea of Fire by caravan will bring you to which hunting ground%?]],  "sanctum of scales" },
    { [[What animal's detailed image lies beneath the waters of the pool located at Cysaegir's Retreat%?]],  "peacock" },
    { [[What was the last name of the halfling wizard who spawned the creatures deep underneath Icemule%?]],  "morpholik" },
    { [[When Kezmon Isle suddenly disappeared, Shubai Dupril searched the waters for weeks but only ever found what%?]],  "bell" },
    { [[The Elemental Confluence can be reached from any major town by using a fully charged what]],  "soulstone" },
    { [[A rolaren gate blocks access to the Ice Plains%.  A rogue can pick it, a sorcerer can cast at it, but what can others do to pass it%?]],  "climb" },
    { [[Terate the Fallen%.  Terate the Chosen%.  Terate of Anwyn%.  What was his surname%?]],  "Niebelun" },
    { [[The Elemental Confluence produces what kind of bulb in its environs%?]],  "glistening engorged bulb" },
    { [[What is the name of the river that is situated to the west of Yuriqen%?]],  "Andemyon" },
    { [[Whose husband stands frozen in ice in the Chamber of the Dead%?]],  "belle" },
    { [[Upon defeating a huge mein golem there is a chance that you could be struck by what]],  "mein shard" },
    { [[What is the name of the proprietress in the Landing's Music Shoppe%?]],  "lute" },
    { [[What creatures inhabit the deserted mines reached by a ferry on Teras]],  "kiramon" },
    { [[Which of Olbin's peaks was the settlement of Reim created from%?]],  "Barmtik" },
    { [[What's the name of the Teras drinking establishment that prefers dwarves and giants]],  "whining elf" },
    { [[What's the name of the ship that sails between Teras and the Landing]],  "Glaesen Star" },
    { [[When searching a lava golem, you must be careful of burning yourself on what%?]],  "fiery red gem" },
    { [[Shubai Dupril built the Pavilion of Bells as a monument to his lost lover%.  What was her Uncle's name]],  "Nyrmont" },
    { [[What is the name of the cliff overlooking the Temple of Luukos on Teras]],  "Lovers' Leap" },
    { [[Which town is the Settlement of Reim closest to%?]],  "icemule trace" },
    { [[This creature's ferocious wing swats are nearly as damaging to hunters as its bite attack%.  It is found only in The Rift%.]],  "aivren" },
    { [[What is the name of the river that sits closest to River's Rest%?]],  "tempest" },
    { [[Which infamous mountain range is the Settlement of Reim located near%?]],  "olbin" },
    { [[Feeding on what blood may remain in your veins after death, this undead creature roams an area east of Yegharren Valley%.]],  "baesrukha" },
    { [[The blue barrier in River's Rest provides passage to what location]],  "citadel" },
    { [[This creature's tree%-like form protects sacred groves and vanishes quickly upon destruction]],  "darkwoode" },
    { [[Who was the proprietor of the Abandoned Inn located in the Upper Trollfang near Wehnimer's Landing]],  "Inger Natanial" },
    { [[What object can kill any adventurer on Teras if they attack it]],  "wasp nest" },
    { [[What shape is the fountain in the Library Aies Courtyard]],  "octagonal" },
    { [[What is the name of the lake that is positioned in between Ta'Illistim and Ta'Vaalor]],  "lake of fear" },
    { [[What was the extinct magical school, once considered a rival to the Hall of Mages]],  "arcanum" },
    { [[There is a slight chance that a soulstone will fall out of the eye socket of which creature]],  "soul golem" },
    { [[What nocturnal creature is the only undead entity to haunt the ruins of Old Ta'Faendryl]],  "lich qyn'arj" },
    { [[This creature's dark, black hide provides a sturdy leather for alterations]],  "vruul" },
    { [[The Elemental Confluence produces what kind of leaf in its environs]],  "razor-edged oily flameleaf" },
    { [[Serving as a connector between Icemule Trace and Pinefar, this treacherous area]],  "nightmare gorge" },
    { [[What wolf%-like, bipedal creatures can be found to the north of Solhaven]],  "shan" },
    { [[Of eyebrow, ear, nail, and fang, which do you get when you skin a ghoul]],  "nail" },
    { [[What sturdy material is Helga's stewpot made from]],  "cast iron" },
    { [[What does the name "Cysaegir" mean]],  "sanctuary" },
    { [[Which lesser spirit favors arthropods%?]],  "arachne" },
    { [[This common, dull grey or blue metal is said to be found deep in caves%.]],  "mithril" },
    { [[Ground orchil lichen will make what color dye%?]],  "pink" },
    { [[This extremely rare metal can only be found in the most remote mountain caves of Elanthia%.]],  "urnon" },
    { [[What stem is best recommended when someone has gone for your jugular%?]],  "aloeas" },
    { [[The geldaralad, the Elven equivalent of a ferroniere, requires a very specific metal]],  "vaalin" },
    { [[This exotic and extremely rare metal is said to be the bane of extraplanar creatures%.  It is also said only the most skilled adventurers can wield this metal%.  %(2 words%)]],  "high steel" },
    { [[Whose quest succeeded when she found the Book of Tormtor%?]],  "despana" },
    { [[What hyphenated potion will cure those little cuts on your countenance%?]],  "rose-marrow" },
    { [[This black, blue speckled metal is one of the most rare metals around%.  It can be found within large meteors]],  "veil iron" },
    { [[Usually tightly woven from reeds and other pieces of nature, this headworn adornment is favored by forest gnomes]],  "basrenne" },
    { [[What root happens to help after you've hurt and healed your head%?]],  "haphip" },
    { [[What potion will unblacken a bruised eye]],  "talneo" },
    { [[What precious gemstone, native to elven lands, is famed for its vaalin inclusions%?]],  "feystone" },
    { [[What berry does the job when acantha is unavailable%?]],  "cuctucae" },
    { [[What area is monkeyflower native to%?  %(2 words%)]],  "teras isle" },
    { [[This magical metal is one of the rarest metals around with limited known mining locations%.  With a misty white and grey swirl coloring]],  "coraesine" },
    { [[What flower will make those constant spasms vanish%?]],  "woth" },
    { [[What rare scarlet gemstone borrows its name from the necromancer who led armies of undead in the Undead War%?]],  "despanal" },
    { [[This dark grey, red%-speckled metal is also referred to as "dwarven steel"%.]],  "invar" },
    { [[How many Stones of Virtue adorn the Drake's crown%?]],  "six" },
    { [[What long%-winded fruit will do the same job as acantha leaf, and then some%?]],  "yabathilium" },
    { [[What hyphenated potion is the enemy of fashionable one%-eyed pirates everywhere%?  %(This answer is hyphenated%.%)]],  "bur-clover" },
    { [[This metal is a ruddy brown color and emits the power of earth%.]],  "gornar" },
    { [[This exotic and extremely rare metal is said to have the power to provide both concussion damage and deleterious side effects%.]],  "low steel" },
    { [[This red, black, or green metal is a quite sturdy and can be found in human coastal communities%.]],  "kelyn" },
    { [[What moss is the most if you've minorly mussed up your abdomen%?]],  "basal" },
    { [[This blue metal can be found deep within peaks that have been covered in snow for longer than any generation%.]],  "rhimar" },
    { [[What is the gnome snowcone vendor's name in Icemule Trace%?]],  "koern" },
    { [[What elven hamlet, midway between Ta'Illistim and Ta'Vaalor, lends its name to a variety of precious ruby%?]],  "sylvarraend" },
    { [[This blue%-streaked black metal forms in small, sharp shards, generally buried or in caves%.]],  "razern" },
    { [[What moss does nothing for hearts, but will mend a broken limb%?]],  "ephlox" },
    { [[What flower is associated with Jastev%?]],  "sirenflower" },
    { [[This halfling archmage was the former leader of the Council of Ten%.]],  "thurfel" },
    { [[This famous wizard moved heaven and earth to ease his recharging of magical objects%.]],  "Melgorehn" },
    { [[This highly magical, deep black metal is extremely rare]],  "urglaes" },
    { [[Who is a popular figurehead for ships%?]],  "niima" },
    { [[This metal is considered the strongest in Elanthia with the ability to disarm opponents%.]],  "adamantine" },
    { [[This light blue metal only forms in caverns at the base of the eastern side of the DragonSpine Mountains%.]],  "veniom" },
    { [[This type of tree can often be found within ancient cemetaries%.]],  "yew" },
    { [[This grey metal is very common and is an all%-purpose metal%.]],  "steel" },
    { [[This gold or red%-gold metal is one of the strongest naturally%-formed metals%.]],  "golvern" },
    { [[What stone is often linked to the tragic lovers Tandrik and Estamil%?]],  "green tourmaline" },
    { [[What flower could be described as acantha's big sister%?]],  "cothinar" },
    { [[Crafted from piecemeal gems and discarded scraps of metal, this Burghal Gnome%-created headworn jewelry]],  "ferrigem" },
    { [[What dark red berry does the job when acantha is unavailable%?]],  "marallis" },
    { [[With its natural nacreous lustre, this fabric is usually patterned with more nature%-inclined designs]],  "flyrsilk" },
    { [[This ornamental, climbing plant has colored flowers]],  "clematis" },
    { [[Passed down from generation to generation, forest gnomes have mastered the craft of weaving individual feather barbs]],  "plumille" },
    { [[This steely, anti%-magic metal blackens over time and use%.]],  "kroderine" },
    { [[This metal is golden in color and extremely rare%.  It is said to give the wielder both an offensive and defensive boost%.]],  "zelnorn" },
    { [[What potion will prepare an item for its third or fourth enchantment%?]],  "duqnuru" },
    { [[What is the sylvan totem animal associated with tourmaline%?]],  "bee" },
    { [[What is the sylvan totem animal associated with agate%?]],  "butterfly" },
    { [[What is the sylvan totem animal associated with emerald%?]],  "hawk" },
    { [[What is the sylvan totem animal associated with jasper%?]],  "hummingbird" },
    { [[What is the sylvan totem animal associated with malachite%?]],  "owl" },
    { [[What is the sylvan totem animal associated with topaz%?]],  "pelican" },
    { [[What is the sylvan totem animal associated with bloodstone%?]],  "snake" },
    { [[What is the sylvan totem animal associated with moonstone%?]],  "wolf" },
    { [[What is the sylvan totem animal associated with zircon%?]],  "turtle" },
    { [[What is the sylvan totem animal associated with sapphire%?]],  "porcupine" },
    { [[What is the sylvan totem animal associated with amber%?]],  "fox" },
    { [[What is the sylvan totem animal associated with pearl%?]],  "rabbit" },
    { [[What is the sylvan totem animal associated with garnet%?]],  "bear" },
    { [[Which Arkati does Zelia greatly dislike%?]],  "Sheru" },
    { [[This metal comes in a brownish color and offers no consistency in properties]],  "bronze" },
    { [[This crystal is a primary ingredient in a deep red potion, used to restore one's health to full%.]],  "n'ayanad" },
    { [[What dusky blue berry does the job when acantha is unavailable%?]],  "cuctucae" },
    { [[What potion will help make your convulsions more controllable%?]],  "bolmara" },
    { [[Which climate would primarily be found in the region of Mount Aenatumgana%?]],  "polar" },
    { [[This black metal is an extremely durable and strong alloy, its forging a skillful blending of mithril]],  "rolaren" },
    { [[Originally worn by Erithian scholars, this piece was meant to channel both their inner mind and status%.]],  "elothrai" },
    { [[This crimson metal is a precious metal to the Elven people%.]],  "eahnor" },
    { [[This light grey metal is one of the more common metals%.]],  "ora" },
    { [[Merely requiring a crafted mithril chain and a very detailed gem, this piece of headworn jewelry]],  "Khazurka" },
    { [[This grey metal is produced through a complicated smelting process%.]],  "Iron" },
    { [[This crystal is a primary ingredient in a lesser health potion%.]],  "s'ayanad" },
    { [[This white metal is a rare variant of its base metal that becomes sanctifield]],  "white ora" },
    { [[What extremely rare metal is celebrate for its ability to morph between forms%?]],  "urnon" },
    { [[What greenery floats serenely around the circumference of the pond in Cysaegir%?]],  "lily pads" },
    { [[What is the name of the first institution of magical learning established in halfling held lands%?]],  "Grinstoff Roth" },
    { [[Which tree possesses shiny brown seeds inside of slightly pitted fruits%?]],  "faewood" },
    { [[What variety of teeth fills Ivas' maw%?]],  "shark" },
    { [[What leaf will bring your blood back to normal in no time%?]],  "acantha" },
    { [[What caverns, found near Ta'Illistim, lend their name to a special variety of diamond%?]],  "maernstrike" },
    { [[What is the sylvan totem animal associated with citrine%?]],  "raccoon" },
    { [[Worn by both men and women giantman, this piece of jewelry is often wrought into stylized knotwork%.]],  "aemikvai" },
    { [[Which flower is said to be worth more than a thousand pirate%-ships of gold%?]],  "buttercup" },
    { [[Mashed gorse will make what color dye%?]],  "yellow" },
    { [[What precious gemstone, found in hues as varied as peach and lilac, is appreciated for its natural ability to glow%?]],  "glimaerstone" },
    { [[Bands of human gypsies and fortunetellers of sorts would attach an oval%-cut gem upon a chain]],  "seer-stone" },
    { [[What leaf will heal scrapes and scratches on hands and limbs%?]],  "ambrominas" },
    { [[Name the storied ancestral blade of the Anodheles bloodline%.]],  "searswathe" },
    { [[This blue and black metal is an alloy of mithril and vultite%.]],  "mithglin" },
}

-- Main loop: read lines and check for trivia questions
while true do
    local line = get()
    for _, entry in ipairs(qa) do
        if string.find(line, entry[1]) then
            fput("answer " .. entry[2])
            break
        end
    end
end
